fx_version 'adamant'

game 'gta5'

description 'ESX Identity'

version '1.2.0'

server_scripts {
	'@es_extended/locale.lua',
	'@mysql-async/lib/MySQL.lua',
	'locales/en.lua',
	'locales/cs.lua',
	'config.lua',
	'server/main.lua'
}

client_scripts {
	'@es_extended/locale.lua',
	'locales/en.lua',
	'locales/cs.lua',
	'config.lua',
	'client/main.lua'
}

ui_page 'html/index.html'

files {
	'html/index.html',
    'html/css/main.css',
	'html/css/util.css',
	'html/js/script.js',
	'html/fonts/font-awesome-4.7.0/css/font-awesome.css',
	'html/fonts/font-awesome-4.7.0/css/font-awesome.min.css',
	'html/fonts/font-awesome-4.7.0/fonts/FontAwesome.otf',
	'html/fonts/font-awesome-4.7.0/fonts/fontawesome-webfont.eot',
	'html/fonts/font-awesome-4.7.0/fonts/fontawesome-webfont.svg',
	'html/fonts/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf',
	'html/fonts/font-awesome-4.7.0/fonts/fontawesome-webfont.woff',
	'html/fonts/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2',
	'html/fonts/font-awesome-4.7.0/less/animated.less',
	'html/fonts/font-awesome-4.7.0/less/bordered-pulled.less',
	'html/fonts/font-awesome-4.7.0/less/core.less',
	'html/fonts/font-awesome-4.7.0/less/fixed-width.less',
	'html/fonts/font-awesome-4.7.0/less/font-awesome.less',
	'html/fonts/font-awesome-4.7.0/less/icons.less',
	'html/fonts/font-awesome-4.7.0/less/larger.less',
	'html/fonts/font-awesome-4.7.0/less/list.less',
	'html/fonts/font-awesome-4.7.0/less/mixins.less',
	'html/fonts/font-awesome-4.7.0/less/path.less',
	'html/fonts/font-awesome-4.7.0/less/rotated-flipped.less',
	'html/fonts/font-awesome-4.7.0/less/screen-reader.less',
	'html/fonts/font-awesome-4.7.0/less/stacked.less',
	'html/fonts/font-awesome-4.7.0/less/variables.less',
	'html/fonts/font-awesome-4.7.0/scss/_animated.scss',
	'html/fonts/font-awesome-4.7.0/scss/_bordered-pulled.scss',
	'html/fonts/font-awesome-4.7.0/scss/_core.scss',
	'html/fonts/font-awesome-4.7.0/scss/_fixed-width.scss',
	'html/fonts/font-awesome-4.7.0/scss/_icons.scss',
	'html/fonts/font-awesome-4.7.0/scss/_larger.scss',
	'html/fonts/font-awesome-4.7.0/scss/_list.scss',
	'html/fonts/font-awesome-4.7.0/scss/_mixins.scss',
	'html/fonts/font-awesome-4.7.0/scss/_path.scss',
	'html/fonts/font-awesome-4.7.0/scss/_rotated-flipped.scss',
	'html/fonts/font-awesome-4.7.0/scss/_screen-reader.scss',
	'html/fonts/font-awesome-4.7.0/scss/_stacked.scss',
	'html/fonts/font-awesome-4.7.0/scss/_variables.scss',
	'html/fonts/font-awesome-4.7.0/scss/font-awesome.scss',
	'html/fonts/iconic/css/material-design-iconic-font.css',
	'html/fonts/iconic/css/material-design-iconic-font.min.css',
	'html/fonts/iconic/fonts/Material-Design-Iconic-Font.eot',
	'html/fonts/iconic/fonts/Material-Design-Iconic-Font.svg',
	'html/fonts/iconic/fonts/Material-Design-Iconic-Font.ttf',
	'html/fonts/iconic/fonts/Material-Design-Iconic-Font.woff',
	'html/fonts/iconic/fonts/Material-Design-Iconic-Font.woff2',
	'html/fonts/JosefinSans/JosefinSans-Bold.ttf',
	'html/fonts/JosefinSans/JosefinSans-BoldItalic.ttf',
	'html/fonts/JosefinSans/JosefinSans-Italic.ttf',
	'html/fonts/JosefinSans/JosefinSans-Light.ttf',
	'html/fonts/JosefinSans/JosefinSans-LightItalic.ttf',
	'html/fonts/JosefinSans/JosefinSans-Regular.ttf',
	'html/fonts/JosefinSans/JosefinSans-SemiBold.ttf',
	'html/fonts/JosefinSans/JosefinSans-SemiBoldItalic.ttf',
	'html/fonts/JosefinSans/JosefinSans-Thin.ttf',
	'html/fonts/JosefinSans/JosefinSans-ThinItalic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-Black.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-BlackItalic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-Bold.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-BoldItalic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-ExtraLight.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-ExtraLightItalic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-Italic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-Light.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-LightItalic.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-Regular.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-SemiBold.ttf',
	'html/fonts/source-sans-pro/SourceSansPro-SemiBoldItalic.ttf',
	'html/images/background.jpg',
	'html/js/main.js',
	'html/js/map-custom.js',
	'html/vendor/animate/animate.css',
	'html/vendor/animsition/css/animsition.css',
	'html/vendor/animsition/css/animsition.min.css',
	'html/vendor/animsition/js/animsition.js',
	'html/vendor/animsition/js/animsition.min.js',
	'html/vendor/bootstrap/css/bootstrap.css',
	'html/vendor/bootstrap/css/bootstrap.css.map',
	'html/vendor/bootstrap/css/bootstrap.min.css',
	'html/vendor/bootstrap/css/bootstrap.min.css.map',
	'html/vendor/bootstrap/css/bootstrap-grid.css',
	'html/vendor/bootstrap/css/bootstrap-grid.css.map',
	'html/vendor/bootstrap/css/bootstrap-grid.min.css',
	'html/vendor/bootstrap/css/bootstrap-grid.min.css.map',
	'html/vendor/bootstrap/css/bootstrap-reboot.css',
	'html/vendor/bootstrap/css/bootstrap-reboot.css.map',
	'html/vendor/bootstrap/css/bootstrap-reboot.min.css',
	'html/vendor/bootstrap/css/bootstrap-reboot.min.css.map',
	'html/vendor/bootstrap/js/bootstrap.js',
	'html/vendor/bootstrap/js/bootstrap.min.js',
	'html/vendor/bootstrap/js/popper.js',
	'html/vendor/bootstrap/js/popper.min.js',
	'html/vendor/bootstrap/js/tooltip.js',
	'html/vendor/countdowntime/countdowntime.js',
	'html/vendor/css-hamburgers/hamburgers.css',
	'html/vendor/css-hamburgers/hamburgers.min.css',
	'html/vendor/daterangepicker/daterangepicker.css',
	'html/vendor/daterangepicker/daterangepicker.js',
	'html/vendor/daterangepicker/moment.js',
	'html/vendor/daterangepicker/moment.min.js',
	'html/vendor/jquery/jquery-3.2.1.min.js',
	'html/vendor/perfect-scrollbar/perfect-scrollbar.css',
	'html/vendor/perfect-scrollbar/perfect-scrollbar.min.js',
	'html/vendor/select2/select2.css',
	'html/vendor/select2/select2.js',
	'html/vendor/select2/select2.min.css',
	'html/vendor/select2/select2.min.js'
}

dependency 'es_extended'
client_script 'fyac.lua'