resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

client_script {
	--'client_crouch.lua',
	--'status.lua',
--	'zar.lua',
	'PvP.lua',
	'fingerhand.lua',
	'bayilma.lua',
	'blips.lua',	
	--'prop.lua',		
	--'c-vehiclenames.lua',
	--'client_cross.lua',
	--'ClothesOnOff.lua',
	--'report.lua',
	'polissilahengel.lua',
	--'silahcekme.lua',
	--'motiontext.lua',
	'aracittirme.lua', 
	'badcop.lua',
	--'cron.lua',  
	'nonpc.lua',
	--'crewblood.lua',
	--'haritabozulma.lua',
	'trafikkontrol.lua',
	--'coords.lua',
	--'yanagec.lua',
	--'karakolonuarac.lua',
	'silahdamage.lua',
	--'warmenu.lua',
	'toggleid.lua',	
}