var tableauQuestion = [
    {   question : "Kara yollarında araç kullanan bir sürücünün aşağıdakilerden hangisini yapması yasaktır?",
        propositionA : "Aksine bir işaret yoksa daralan yol kesimlerinde yüklü araçlara geçiş kolaylığı sağlaması",
        propositionB : "Kavşağa geldiğinde varsa kurallara uygun olarak karşıya geçen yayalara geçiş hakkını vermesi",
        propositionC : "Kavşaklarda, demir yolu geçitlerinde ve buralara yaklaşırken öndeki aracı geçmesi",
        propositionD : "Geçiş üstünlüğü bulunan bir aracın duyulur veya görülür işaretini aldığında, bu araçların kolayca ilerlemelerini sağlamak için taşıt yolu üzerinde yer açması",
        reponse : "C"},
		
    {   question : "Bir kavşakta sağa dönecek olan sürücünün aşağıdakilerden hangisini yapması yanlıştır?",
        propositionA : "Hızını azaltması",
        propositionB : "Dönüş işareti vermesi",
        propositionC : "Geniş bir kavisle dönmesi",
        propositionD : "Sağ şeride veya işaretlerle dönüş izni verilen şeride girmesi",
        reponse : "C"},
		
    {   question : "Geceleyin otoyolda seyir hâlindeyken öndeki araç sürücüsünü rahatsız etmemek için aracın hangi ışıkları kullanılmalıdır?",
        propositionA : "Yakını gösteren",
        propositionB : "Sadece park",
        propositionC : "Sis",
        propositionD : "Uzağı gösteren",
        reponse : "A"},
	
	{   question : "Frene basıldığı andan itibaren, aracın durmasına kadar geçen sürede katedilen yola “fren mesafesi” denir. Buna göre aşağıdakilerden hangisi fren mesafesini etkileyen faktörlerden biri değildir?",
        propositionA : "Aracın hızı",
        propositionB : "İklim koşulları",
        propositionC : "Aracın yük durumu",
        propositionD : "Yolun genişliği",
        reponse : "D"},
		
	{   question : "Aşağıdakilerden hangisi trafikte çevreyi korumaya yönelik davranışlardandır?",
        propositionA : "Sigara izmaritlerinin araç dışına atılması",
        propositionB : "Motor yağı, asit vb. maddelerin toprağa dökülmesi",
        propositionC : "Zorunluluk dışında korna çalmaktan uzak durulması",
        propositionD : "Dökülecek, tozacak ve taşacak şekilde yük taşınması",
        reponse : "C"},
		
	{   question : "Dizel motor kullanan bir araca yanlışlıkla benzin konulması durumunda aşağıdakilerden hangisinin yapılması uygundur?",
        propositionA : "Aracın düşük hızda sürülmesi",
        propositionB : "Lastik hava basınçlarının düşürülmesi",
        propositionC : "Aracın yüksek devirde kullanılması",
        propositionD : "Yakıt deposunun boşaltılması",
        reponse : "D"},
	
	{   question : "Trafikte kırmızı ışıkta beklerken ışık sarıya döner dönmez önündeki araca korna çalan, ışığın yeşile dönmesi için 1 saniye bile bekleyemeyen sürücünün bu davranışı için aşağıdakilerden hangisi söylenebilir?",
        propositionA : "Saygılı",
        propositionB : "Telaşsız",
        propositionC : "Orospu Çocuğu",
        propositionD : "Efendi",
        reponse : "C"},
		
	{   question : "Yaz aylarında kış lastiklerinin kullanılması aşağıdakilerden hangisine neden olur?",
        propositionA : "Aracın maksimum hızının artmasına",
        propositionB : "Yakıt tüketiminin azalmasına",
        propositionC : "Lastiklerin daha çabuk aşınmasına",
        propositionD : "Fren sisteminin arızalanmasına",
        reponse : "C"},
		
	{   question : "Motor hareketinin vites kutusuna iletilmesini sağlayan sistem aşağıdakilerden hangisidir?",
        propositionA : "Kavrama",
        propositionB : "Ateşleme",
        propositionC : "Şarj",
        propositionD : "Marş",
        reponse : "D"},
		
	{   question : "Seyahate başlamadan önce koltuk ve ayna ayarlarının yapılmasının sebebi aşağıdakilerden hangisidir?",
        propositionA : "Yakıt tüketimini azaltmak",
        propositionB : "Lastiklerin ömrünü uzatmak",
        propositionC : "Aracın ivmelenme süresini artırmak",
        propositionD : "Sürüş konforu ve güvenliğini sağlamak",
        reponse : "D"},
]
