CREATE TABLE `cylex_give_money` (
	`Gonderen` VARCHAR(50) NULL DEFAULT NULL,
	`Tip` VARCHAR(50) NULL DEFAULT NULL,
	`Sayi` INT(11) NULL DEFAULT NULL,
	`Alici` VARCHAR(50) NULL DEFAULT NULL,
	`Zaman` TIMESTAMP NULL DEFAULT current_timestamp()
)
COMMENT='ESYA, PARA VERME LOGLARI'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cylex_give` (
	`Veren` VARCHAR(50) NULL DEFAULT NULL,
	`Tip` VARCHAR(50) NULL DEFAULT NULL,
	`Sayi` INT(25) NULL DEFAULT NULL,
	`Item` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_turkish_ci',
	`Alici` VARCHAR(50) NULL DEFAULT NULL,
	`Zaman` TIMESTAMP NULL DEFAULT current_timestamp()
)
COMMENT='EŞYA, PARA VERME LOGLARI'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cylex_drop` (
	`Atan` VARCHAR(50) NULL DEFAULT NULL,
	`Tip` VARCHAR(50) NULL DEFAULT NULL,
	`Item` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_turkish_ci',
	`Sayi` BIGINT(50) NULL DEFAULT NULL,
	`Zaman` TIMESTAMP NULL DEFAULT current_timestamp()
)
COMMENT='YERE ATMA LOGLARI'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
